# Chapter - 5
COLLECTIONS

# Tuple

In [1]:
a = (1, "string", 1.0)

(1, "string", 1.0)

In [2]:
typeof(a) 


Tuple{Int64, String, Float64}

In [3]:
a[1]

1

In [4]:
a[1] = 6    

LoadError: MethodError: no method matching setindex!(::Tuple{Int64, String, Float64}, ::Int64, ::Int64)

In [5]:
b, c = a                          
(1, "string", 1.0)

(1, "string", 1.0)

In [6]:
b

1

In [7]:
c

"string"

# N Tuple

In [8]:
NTuple{3, Int}

Tuple{Int64, Int64, Int64}

In [9]:
a = ntuple(x->4, 10)

(4, 4, 4, 4, 4, 4, 4, 4, 4, 4)

In [10]:
typeof(a)

NTuple{10, Int64}

In [11]:
a = ntuple(i->i*1.0, 10)

(1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0, 9.0, 10.0)

In [12]:
typeof(a)

NTuple{10, Float64}

# Tuple as a Collection

In [13]:
length(a)

10

In [14]:
for i=1:length(a)
    println(a[i])
end

1.0
2.0
3.0
4.0
5.0
6.0
7.0
8.0
9.0
10.0


# Integers as Type Parameters

In [15]:
struct Point{N}
    data::NTuple{N, Float32}
    Point(d...)=new{length(d)}(d)
end
const Point2D=Point{2}
const Point3D=Point{3}

function dist(p1::Point2D, p2::Point2D)
    dx, dy = (p1.data[1] - p2.data[1], p1.data[2] - p2.data[2])
    return sqrt(dx*dx+dy*dy)
end
function dist(p1::Point3D, p2::Point3D)
    dx, dy, dz = (p1.data[1] - p2.data[1], 
                  p1.data[2] - p2.data[2], 
                  p1.data[3] - p2.data[3])
    return sqrt(dx*dx+dy*dy+dz*dz)
end

dist (generic function with 2 methods)

In [16]:
dist(Point(1, 2), Point(3, 4))

2.828427f0

In [17]:
dist(Point(1, 2, 3), Point(3, 4, 5))

3.4641016f0

In [18]:
function dist(p1::Point{N}, p2::Point{N}) where N
    sumval = 0f0
    for i=1:N
        d = p1.data[i] - p2.data[i]
        sumval += d*d
    end
    return sqrt(sumval)
end

dist (generic function with 3 methods)

In [19]:
dist(Point(1, 2), Point(3, 4))

2.828427f0

In [20]:
dist(Point(1, 2, 3), Point(3, 4, 5))

3.4641016f0

In [21]:
function dist(p1::Point, p2::Point)
    N = length(p1.data)
    sumval = 0f0
    for i=1:N
        d = p1.data[i] - p2.data[i]
        sumval += d*d
    end
    return sqrt(sumval)
end

dist (generic function with 4 methods)

In [22]:
dist(Point(1, 2), Point(3, 4))

2.828427f0

In [23]:
dist(Point(1f0, 2f0, 3f0), Point(1, 2))

LoadError: BoundsError: attempt to access Tuple{Float32, Float32} at index [3]

In [24]:
function dist(p1::Point{N}, p2::Point{N}) where N
    sumval = 0f0
    for i=1:N
        d = p1.data[i] - p2.data[i]
        sumval += d*d
    end
    return sqrt(sumval)
end

function dist(p1::Point{N1}, p2::Point{N2}) where {N1, N2}
    N1 > N2 && return dist(p2, p1)
    tp = Point(p1.data..., ntuple(i->0f0, N2-N1)...)
    return dist(tp, p2)
end

dist (generic function with 4 methods)

In [25]:
dist(Point(1f0, 2f0, 3f0), Point(1, 2))

3.0f0

# Value Parameters

In [26]:
struct MyVal{N}
    MyVal(N)=new{N}()
end
f(::MyVal{N}) where N = N
function f(::MyVal{1})
    println("Called from 1")
end

f (generic function with 2 methods)

In [27]:
f(MyVal(2))

2

In [28]:
f(MyVal(1))

Called from 1


# Singleton

In [29]:
MyVal(1) === MyVal(1)

true

In [30]:
MyVal(1) === MyVal(2)

false

In [31]:
MyVal(:a)

MyVal{:a}()

# Ranges
Unit Range

In [32]:
a=1:5
typeof(a)

UnitRange{Int64}

In [33]:
for i=a
    println(i)
end

1
2
3
4
5


StepRange

In [34]:
b=1:2:5
typeof(b)

StepRange{Int64, Int64}

In [35]:
for i=b
    println(i)
end

1
3
5


Decreasing Ranges

In [36]:
c=5:-1:1
typeof(c)

StepRange{Int64, Int64}

In [37]:
for i=c
    println(i)
end

5
4
3
2
1


In [38]:
d = 1:2.1:6.0

1.0:2.1:5.2

In [39]:
typeof(d)

StepRangeLen{Float64, Base.TwicePrecision{Float64}, Base.TwicePrecision{Float64}}

# Array

In [40]:
v = [1, 2, 3]

3-element Vector{Int64}:
 1
 2
 3

In [41]:
m = [1 2 3]

1×3 Matrix{Int64}:
 1  2  3

In [42]:
m1 = [1 2 3; 4 5 6]

2×3 Matrix{Int64}:
 1  2  3
 4  5  6

In [43]:
m2 = [1 2; 3 4; 5 6]

3×2 Matrix{Int64}:
 1  2
 3  4
 5  6

Memory Layout and Indexing

In [44]:
m1[1, 2]

2

In [45]:
m1[2, 2]

5

In [46]:
m2[1, 2]

2

In [47]:
m2[2, 2]

4

# Constructors

In [48]:
Array{Int}(undef, 1, 2)

1×2 Matrix{Int64}:
 267014240  305915984

In [49]:
Array{Int}(undef, 2)

2-element Vector{Int64}:
 256446720
 275744848

In [50]:
Array{Int, 2}(undef, (2, 3))

2×3 Matrix{Int64}:
 306919648  306919680  242221232
 306919664  242221744         -1

In [51]:
Array{Float32}(undef, (2, 3))

2×3 Matrix{Float32}:
 7.75075f26  3.07051f-28  2.57729f26
 0.0         0.0          0.0

In [52]:
struct A
    i::Int
    f::Float64
end
a = A(1, 1); isbits(a)

true

In [53]:
aarr = Array{A}(undef, (2, 2))

2×2 Matrix{A}:
 A(261062208, 1.23421e-315)  A(261195104, 1.29048e-315)
 A(261194944, 1.29047e-315)  A(251451120, 1.29048e-315)

In [54]:
struct T
    a::A
    b
end
b = T(A(1, 1), 1); isbits(b)

false

In [55]:
barr = Array{T}(undef, (2, 2))

2×2 Matrix{T}:
 #undef  #undef
 #undef  #undef

In [56]:
barr[1,1] = barr[2,1] = barr[1,2] = barr[2,2] = b

T(A(1, 1.0), 1)

In [57]:
barr

2×2 Matrix{T}:
 T(A(1, 1.0), 1)  T(A(1, 1.0), 1)
 T(A(1, 1.0), 1)  T(A(1, 1.0), 1)

In [58]:
Vector{Int}(undef, 3)

3-element Vector{Int64}:
         1
 296322000
         1

In [59]:
Matrix{Int}(undef, 3, 3)

3×3 Matrix{Int64}:
        17         20         34
         4          5         10
 275602945  275603201  275603201

In [60]:
zeros(Float32, (2, 3))

2×3 Matrix{Float32}:
 0.0  0.0  0.0
 0.0  0.0  0.0

In [61]:
ones(Float32, (2, 3))

2×3 Matrix{Float32}:
 1.0  1.0  1.0
 1.0  1.0  1.0

In [62]:
ones(UInt8, (2, 3))

2×3 Matrix{UInt8}:
 0x01  0x01  0x01
 0x01  0x01  0x01

In [63]:
zb = zeros(Bool, (8, 8))

8×8 Matrix{Bool}:
 0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0

In [64]:
sizeof(zb)

64

In [65]:
z = falses(8, 8)

8×8 BitMatrix:
 0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0

In [66]:
sizeof(z)

8

Fill and similar

In [67]:
a = fill(5.0, (2, 2))

2×2 Matrix{Float64}:
 5.0  5.0
 5.0  5.0

In [68]:
a = fill(5, (2, 2))

2×2 Matrix{Int64}:
 5  5
 5  5

In [69]:
b = similar(a, Int)

2×2 Matrix{Int64}:
 1805302992  1801960096
  265038640   273420368

Collect

In [70]:
collect(1:3)

3-element Vector{Int64}:
 1
 2
 3

In [71]:
collect(Float64, 1:2:3)

2-element Vector{Float64}:
 1.0
 3.0

reshape

In [72]:
a = collect(1:16)

16-element Vector{Int64}:
  1
  2
  3
  4
  5
  6
  7
  8
  9
 10
 11
 12
 13
 14
 15
 16

In [73]:
b = reshape(a, (4, 4))

4×4 Matrix{Int64}:
 1  5   9  13
 2  6  10  14
 3  7  11  15
 4  8  12  16

In [74]:
c = reshape(b, (2, 8))

2×8 Matrix{Int64}:
 1  3  5  7   9  11  13  15
 2  4  6  8  10  12  14  16

In [75]:
d = reshape(c, (8, 2))

8×2 Matrix{Int64}:
 1   9
 2  10
 3  11
 4  12
 5  13
 6  14
 7  15
 8  16

hcat, vcat and hcat

In [76]:
vcat([1 2; 3 4], [5 6; 7 8], [9 10; 11 12])

6×2 Matrix{Int64}:
  1   2
  3   4
  5   6
  7   8
  9  10
 11  12

In [77]:
hcat([1 2; 3 4], [5 6; 7 8], [9 10; 11 12])

2×6 Matrix{Int64}:
 1  2  5  6   9  10
 3  4  7  8  11  12

In [78]:
hvcat((2, 2, 2), [1, 2], [3, 4], [5, 6], [7, 8], [9, 10], [11, 12])

6×2 Matrix{Int64}:
  1   3
  2   4
  5   7
  6   8
  9  11
 10  12

In [79]:
hvcat(6, [1, 2], [3, 4], [5, 6], [7, 8], [9, 10], [11, 12])

2×6 Matrix{Int64}:
 1  3  5  7   9  11
 2  4  6  8  10  12

# Associative Collection

Dict

In [ ]:
d = Dict("a"=>1, "c"=>2, "b"=>3)

In [ ]:
d["b"]

In [ ]:
d["a"] = 5

In [ ]:
println(d)

In [ ]:
d = Dict("a"=>1, "c"=>2, "b"=>3, "a"=>4)

get Methods

In [ ]:
get(d, "a", 3)

In [ ]:
get(d, "e", 0)

In [ ]:
getindex(d, "e")

In [ ]:
d["e"]

In [ ]:
get!(d, "a", 0)

In [ ]:
get!(d, "e", 0)

In [ ]:
d

setindex! Method

In [ ]:
d["e"] = 10

In [ ]:
setindex!(d, 11, "e")

# Set

In [ ]:
s = Set([2 3 4 5 1 2 3])

In [ ]:
6 in s

In [ ]:
5 in s

In [ ]:
t = Set([4 5 7 8 9])

# Union and Intersection

In [ ]:
union(s, t)

In [ ]:
intersect(s, t)

In [ ]:
union!(s, t)

In [ ]:
s

# Iteration

for loop

In [ ]:
for i=5:-2:1
    println(i)
end

In [ ]:
b = [1.0 2 3; 4 5 6; 7 8 9]
for i=b
    println(i)
end

In [ ]:
for p in d
    println(p)
end

In [ ]:
for (k, v) in d
    println("Key:", k," Value:", v)
end

function...do

In [ ]:
function collect_square(v)
    a = similar(v)
    for i=1:length(v)
        a[i] = v[i]*v[i]
    end
    return a
end
collect_square(1:4)

In [ ]:
function collect_function(f::Function, v)
    a = similar(v)
    for i=1:length(v)
        a[i] = f(v[i])
    end
    return a
end
collect_function(x->x^3, 1:4)

In [ ]:
collect_function(1:4) do x
    return x^3
end

In [ ]:
map(1:4) do x
    return x^3
end

# Iteration Framework

In [ ]:
v = collect(3:2:10)

In [ ]:
for i=v
    println(i)
end

In [ ]:
next = iterate(v)

In [ ]:
while next !== nothing
    value, state = next
    println(value)
    next = iterate(v, state)
end

# iterate Methods|

# Optional Methods

In [ ]:
Base.IteratorSize(Vector{Int})

In [ ]:
Base.IteratorEltype(Vector{Int})

In [ ]:
eltype(Vector{Int})

# Example

In [ ]:
struct Squares
    value::Int
end
Base.iterate(s::Squares) = s.value <= 0 ? nothing : (1, 2)

Base.iterate(s::Squares, state) = s.value < state ? nothing :      
    (state*state, state+1)

In [ ]:
for i=Squares(3)
    println(i)
end

In [ ]:
collect(Squares(3))

In [ ]:
Base.length(s::Squares)=s.value

In [ ]:
collect(Squares(3))

In [ ]:
Base.eltype(::Type{Squares})=Int

In [ ]:
eltype(Squares)

In [ ]:
collect(Squares(3))

# Generators and Comprehensions

In [ ]:
[i*i for i=1:3]

In [ ]:
[i*j for i=1:3, j=1:3]

In [ ]:
[i*j for i=1:3 for j=i:3]

In [ ]:
gen=(i*j for i=1:3 for j=i:3)

In [ ]:
for v=gen
    println(v)
end